{
 "title": "IPMI Exporter",
 "description": "Dashboard for Prometheus IPMI Exporter\r\nhttps://github.com/srkaviani/prometheus_exporters/tree/main/ipmi_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_chassis_power_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Machine Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 0 },
   "targets": [
    { "expr": "ipmi_bmc_info" }
   ]
  },
  {
   "title": "Fan Speed State",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_fan_speed_state", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Fan speed in rotations per minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_fan_speed_rpm", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Power Consumption watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_power_state", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Power reading in Watts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_power_watts", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "IPMI Sensors State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "ipmi_sensor_state" }
   ]
  },
  {
   "title": "Temperature State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_temperature_state", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_temperature_celsius", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Reported state of a voltage sensor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_voltage_state", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Voltage reading in Volts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ipmi_voltage_volts", "legendFormat": "{{name}}" }
   ]
  }
 ]
}